console.log("Hello! I'm your coding fun fact guide!");
let botName = "Sebastian";
let botLocation = "Dylan's laptop";
let favoriteLanguage = "Java";
console.log("My name is " + botName + " and I live on " + botLocation + ".");
console.log("My favorite programming language is "+ favoriteLanguage + ".");
let codingFact = ("My favorite coding language, " + favoriteLanguage + ", uses strings like this.");
console.log(codingFact);
codingFact = ("A new fact about " + favoriteLanguage + " is that it is the first coding language Dylan is learning.");
console.log(codingFact);
codingFact = ("A third fact about " + favoriteLanguage + " is that it is also a name for coffee.");
console.log(codingFact);
console.log("It was fun sharing these facts with you. Goodbye! - " + botName + " from " + botLocation + ".");